'use strict';
const $=id=>document.getElementById(id);
let csrf='',dataset=null,lastStudy=null;
let eventRetry=null,reviewKey=crypto.randomUUID();
function tell(message,error=false){const el=$('message');el.hidden=false;el.textContent=message;el.classList.toggle('error',error);}
function node(tag,value,cls){const e=document.createElement(tag);if(value!==undefined)e.textContent=String(value);if(cls)e.className=cls;return e;}
function view(name){document.querySelectorAll('[data-panel]').forEach(e=>e.hidden=e.dataset.panel!==name);document.querySelectorAll('.sidebar [data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===name));if(name==='archive')loadDocuments().catch(e=>tell(e.message,true));}
document.querySelectorAll('[data-view]').forEach(e=>e.addEventListener('click',()=>view(e.dataset.view)));
async function api(path,payload){const opts={headers:{},signal:AbortSignal.timeout(60000)};if(payload!==undefined){opts.method='POST';opts.headers={'Content-Type':'application/json','X-Invest-CSRF':csrf};opts.body=JSON.stringify(payload);}const response=await fetch(path,opts);const type=response.headers.get('Content-Type')||'';const data=type.includes('json')?await response.json():await response.blob();if(!response.ok)throw new Error(data.error||`请求失败 (${response.status})`);return data;}
function action(id,fn,event='click'){$(id).addEventListener(event,async ev=>{ev.preventDefault();const el=ev.currentTarget;const button=el.tagName==='FORM'?el.querySelector('[type=submit]'):el;button.disabled=true;try{await fn(ev);}catch(e){tell(e.message||String(e),true);}finally{button.disabled=false;}});}
function table(target,headers,rows){const wrapper=node('div',undefined,'table-wrap'),t=node('table'),head=node('thead'),hr=node('tr');headers.forEach(h=>hr.append(node('th',h)));head.append(hr);t.append(head);const body=node('tbody');rows.forEach(row=>{const r=node('tr');row.forEach(cell=>{const td=node('td');cell instanceof Node?td.append(cell):td.textContent=String(cell??'—');r.append(td);});body.append(r);});t.append(body);wrapper.append(t);target.replaceChildren(wrapper);}
function pretty(target,value){target.replaceChildren(node('pre',JSON.stringify(value,null,2)));}
function metrics(target,items){const wrap=node('div',undefined,'metrics');items.forEach(([label,value])=>{const m=node('div',undefined,'metric');m.append(node('small',label),node('strong',value??'—'));wrap.append(m);});target.replaceChildren(wrap);}
function download(value,name){const blob=value instanceof Blob?value:new Blob([JSON.stringify(value,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const pct=x=>x===null||x===undefined?'—':(Number(x)*100).toFixed(2)+'%';
async function loadDatasets(selected){const r=await api('/api/datasets');const keep=selected||$('dataset').value;$('dataset').replaceChildren(new Option('请选择数据集',''));r.datasets.forEach(d=>$('dataset').add(new Option(`${d.meta.source_kind==='demo'?'[合成] ':''}${d.start} → ${d.end} · ${d.rows}行 · ${d.id.slice(0,8)}`,d.id)));if(r.datasets.some(d=>d.id===keep))$('dataset').value=keep;if($('dataset').value)await chooseDataset();}
async function chooseDataset(){if(!$('dataset').value){dataset=null;return; }dataset=await api('/api/datasets/'+$('dataset').value);const symbols=[...new Set(dataset.bars.map(b=>b.symbol))];$('study-symbol').replaceChildren(...symbols.map(s=>new Option(s,s)));$('source-banner').textContent=(dataset.meta.source_kind==='demo'?'合成演示 · 不是真实行情。 ':'导入数据 · 来源真实性与许可未独立核验。 ')+dataset.meta.source;pretty($('audit-output'),dataset.audit);}
function needDataset(){if(!dataset)throw new Error('请先载入或选择数据集');return dataset.id;}
action('dataset',chooseDataset,'change');
action('demo',async()=>{const d=await api('/api/datasets/demo',{});await loadDatasets(d.id);tell('合成演示已载入。数据与结果不代表真实投资表现。');});
action('receipt',async()=>{const d=await api('/api/workbench/receipt',{dataset_id:needDataset(),declaration:{license_note:$('license').value}});pretty($('receipt-output'),d);tell('审计回执已保存，未把来源声明提升为独立核验。');});
action('study-form',async()=>{const r=await api('/api/workbench/study',{dataset_id:needDataset(),specification:{symbol:$('study-symbol').value,initial_cash:Number($('study-cash').value),candidates:JSON.parse($('candidates').value),cost_model_acknowledged:$('cost-ack').checked}});lastStudy=r;const p=r.payload;metrics($('study-output'),[['计划实验',p.summary.planned],['算术回放通过',p.summary.succeeded],['保留的失败',p.summary.failed]]);const out=node('div');table(out,['样本段','候选','成本','状态','收益','买入持有','相对基准 / 失败原因'],p.results.map(row=>[row.period,row.candidate,row.cost,row.status==='PASS'?'通过':'失败',pct(row.result?.metrics.total_return),pct(row.result?.metrics.benchmark_return),row.reason||pct(row.excess_vs_buy_hold)]));$('study-output').append(out,node('p',p.limitations.join('；')));$('study-export').hidden=false;tell(`已保存 ${p.summary.planned} 项实验，失败 ${p.summary.failed} 项。未打开冻结留出集。`);},'submit');
action('study-export',async()=>download(lastStudy,'Invest-study-'+lastStudy.id.slice(0,12)+'.json'));
async function loadReviews(selected){const r=await api('/api/workbench/documents?kind=review');const keep=selected||$('review-select').value;$('review-select').replaceChildren(new Option('请选择复盘账户',''));r.documents.forEach(d=>$('review-select').add(new Option(d.name,d.id)));if(r.documents.some(d=>d.id===keep))$('review-select').value=keep;if($('review-select').value)await refreshReview();}
function showReview(r){const s=r.state;metrics($('review-output'),[['现金 / 元',s.cash],['按末次价格净资产',s.net_assets_on_last_marks],['观测点时间加权收益',pct(s.time_weighted_return)]]);const detail=node('div');table(detail,['资金净流入','股息','累计费用','估值口径利润'],[[s.net_external_flows,s.cash_dividends,s.total_fees,s.profit_on_last_marks]]);$('review-output').append(detail,node('p',s.warnings.join('；')));if(s.positions.length){const ps=node('div');table(ps,['标的','股数','末次估值价格','估值时间'],s.positions.map(p=>[p.symbol,p.quantity,p.marked_price,p.marked_at]));$('review-output').append(ps);}table($('events-output'),['序号','事件','发生时间','服务器记录时间','哈希'],r.events.map(e=>[e.sequence,e.event.type,e.event.occurred_at,e.recorded_at,e.hash.slice(0,16)]));}
async function refreshReview(){if(!$('review-select').value)return;showReview(await api('/api/workbench/review?id='+$('review-select').value));}
action('review-select',refreshReview,'change');
action('review-form',async()=>{const d=await api('/api/workbench/reviews',{name:$('review-name').value,initial_cash:$('review-cash').value,manual_record_acknowledged:$('manual-ack').checked,client_key:reviewKey});reviewKey=crypto.randomUUID();await loadReviews(d.id);tell('人工复盘账户已创建。');},'submit');
const eventDefaults={DEPOSIT:{amount:'1000.00'},WITHDRAWAL:{amount:'1000.00'},FEE:{amount:'5.00'},DIVIDEND:{symbol:'600000.SH',amount:'10.00'},BUY:{symbol:'600000.SH',quantity:100,price:'10.00',fee:'5.00'},SELL:{symbol:'600000.SH',quantity:100,price:'11.00',fee:'5.00'},MARK:{prices:{'600000.SH':'10.50'}},DECISION:{reason:'记录支持证据、反证与判断失效条件',evidence_at:'2024-01-01T16:00:00+08:00'},FAILURE:{reason:'数据更新失败，未生成替代结果'},RETRY:{reason:'记录重试对象、原因和结果'}};
$('event-type').addEventListener('change',()=>{$('event-fields').value=JSON.stringify(eventDefaults[$('event-type').value],null,2);});
action('event-form',async()=>{const review_id=$('review-select').value;if(!review_id)throw new Error('先创建或选择复盘账户');const event={...JSON.parse($('event-fields').value),type:$('event-type').value,occurred_at:$('event-time').value,source:$('event-source').value};const signature=JSON.stringify({review_id,event});if(!eventRetry||eventRetry.signature!==signature)eventRetry={signature,key:crypto.randomUUID()};const result=await api('/api/workbench/event',{review_id,event_key:eventRetry.key,event});showReview(result);eventRetry=null;tell('事件已校验并追加。哈希链与现金余额已重新核对。');},'submit');
async function loadDocuments(){const kind=$('document-kind').value;const r=await api('/api/workbench/documents?kind='+kind);table($('documents-output'),['身份 / 名称','保存时间','操作'],r.documents.map(d=>{const b=node('button','导出 JSON','secondary');b.addEventListener('click',async()=>{try{download(await api('/api/workbench/document?id='+d.id),'Invest-'+kind+'-'+d.id.slice(0,12)+'.json');}catch(e){tell(e.message,true);}});return[d.name,d.recorded_at,b];}));}
action('refresh-documents',loadDocuments);action('document-kind',loadDocuments,'change');
action('backup',async()=>{if(!$('backup-ack').checked)throw new Error('请先确认备份包含私人账本和笔记');download(await api('/api/private-backup',{confirm_private_export:true}),'Invest-complete-private-backup.zip');tell('完整备份已生成。请妥善保存私人数据。');});
const sampleFacts={source_name:'合成财务事实样例，不对应真实公司披露',source_text:'虚构指标：2023年末利润；2024-03-01首次披露10，2024-05-01修订为8。仅测试时点过滤。',license_note:'人工合成测试，不含真实公告数据',facts:[{symbol:'600000.SH',metric:'net_profit',period_end:'2023-12-31',available_at:'2024-03-01T16:00:00+08:00',revision:1,value:'10',unit:'CNY million'},{symbol:'600000.SH',metric:'net_profit',period_end:'2023-12-31',available_at:'2024-05-01T16:00:00+08:00',revision:2,value:'8',unit:'CNY million'}]};
action('facts-example',async()=>{$('facts-json').value=JSON.stringify(sampleFacts,null,2);tell('已填入明确标注的合成事实样例，尚未保存。');});
async function loadFacts(selected){const r=await api('/api/workbench/documents?kind=facts');const keep=selected||$('facts-select').value;$('facts-select').replaceChildren(new Option('请选择事实包',''));r.documents.forEach(d=>$('facts-select').add(new Option(d.name,d.id)));if(r.documents.some(d=>d.id===keep))$('facts-select').value=keep;}
action('facts-import',async()=>{const d=await api('/api/workbench/facts',{enabled:$('facts-enabled').checked,bundle:JSON.parse($('facts-json').value)});await loadFacts(d.id);tell('事实包已校验保存。来源和可见时间仍属于声明信息。');});
action('facts-query',async()=>{const r=await api('/api/workbench/as-of',{enabled:$('facts-enabled').checked,bundle_id:$('facts-select').value,symbol:$('facts-symbol').value,as_of:$('facts-time').value});pretty($('facts-output'),r);tell(r.enabled?`选中当时已可见的 ${r.facts.length} 条事实。`:'扩展已关闭，未读取事实包，核心研究不受影响。');});
async function loadVersion(){const r=await api('/api/workbench/status');if(typeof r.version!=='string'||!r.version)throw new Error('版本信息不可用');$('app-version').textContent=r.version;}
(async()=>{try{csrf=(await api('/api/config')).csrf_token;await Promise.all([loadVersion(),loadDatasets(),loadReviews(),loadFacts()]);}catch(e){tell('初始化未完成：'+e.message,true);}})();
