const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const assert = require('assert');
const path = require('path');
const root = path.resolve(__dirname, '../..');
const out = process.env.INVEST_REVIEW_OUTPUT || require('os').tmpdir();
(async () => {
 const browser = await chromium.launch({...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page = await browser.newPage({viewport:{width:1365,height:1000},acceptDownloads:true});
 const errors=[]; const failures=[];
 page.on('pageerror',e=>errors.push(String(e)));
 page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('400')&&!m.text().includes('404')) failures.push(m.text())});
 const checks=[]; const record=x=>checks.push(x);
 try {
  await page.goto(process.env.INVEST_REVIEW_URL || 'http://127.0.0.1:8771', {waitUntil:'networkidle'});
  await page.locator('#load-demo').click();
  await page.locator('#research-content').waitFor({state:'visible'});
  await page.locator('#demo-notice').waitFor({state:'visible'});
  await page.waitForFunction(()=>document.querySelectorAll('#research-cards .research-card').length===2);
  record('合成示例、两证券研究与明确来源');
  await page.screenshot({path:path.join(out, 'invest-desktop.png'),fullPage:true});
  await page.locator('#tab-backtest').click();
  await page.locator('#backtest-symbol').selectOption('600000.SH');
  await page.locator('#backtest-form [name=cost_model_acknowledged]').check();
  await page.locator('#backtest-form button[type=submit]').click();
  await page.locator('#backtest-results').waitFor({state:'visible'});
  assert(await page.locator('#equity-chart svg').count()>0);
  assert(await page.locator('#trade-table tbody tr').count()>0);
  record('回测表单、费用确认、净值SVG及成交明细');
  await page.screenshot({path:path.join(out, 'invest-backtest.png'),fullPage:true});
  await page.locator('#tab-paper').click();
  await page.locator('#account-name').fill('独立浏览器模拟账户');
  await page.locator('#account-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#account-select').value);
  await page.locator('#paper-symbol').selectOption('600000.SH');
  await page.locator('#paper-date').fill('2024-01-02');
  await page.locator('#paper-quantity').fill('100');
  await page.locator('#paper-reason').fill('只验证模拟流程；数据完全合成');
  await page.locator('#paper-trade-form [name=cost_model_acknowledged]').check();
  await page.locator('#record-trade').click();
  await page.waitForFunction(()=>document.querySelectorAll('#paper-trade-table tbody tr').length===1);
  await page.locator('#paper-side').selectOption('SELL');
  await page.locator('#paper-reason').fill('检验同日卖出受限');
  await page.locator('#paper-trade-form [name=cost_model_acknowledged]').check();
  await page.locator('#record-trade').click();
  await page.waitForFunction(()=>document.querySelector('#message').textContent.includes('T+1'));
  assert.equal(await page.locator('#paper-trade-table tbody tr').count(),1);
  record('账户保存、买入成功、同日卖出拒绝且账本未变');
  for(const [id,value] of Object.entries({'note-symbol':'600000.SH','note-thesis':'<img src=x onerror="window.__xss=1">','note-evidence':'合成数据的流程验收','note-risks':'不是实际市场证据','note-invalidation':'真实样本不支持时重新评估','note-source':'https://example.com/evidence'})) await page.locator('#'+id).fill(value);
  await page.locator('#note-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#message').classList.contains('error'));
  await page.locator('#note-thesis').fill('安全笔记：合成数据流程验收');
  await page.locator('#note-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#notes-list').textContent.includes('安全笔记'));
  assert.equal(await page.evaluate(()=>window.__xss),undefined);
  assert.equal(await page.locator('#notes-list img').count(),0);
  record('研究笔记拒绝HTML并存储安全文本');
  const downloadP=page.waitForEvent('download');
  await page.locator('#export-data').click();
  const download=await downloadP;
  await download.saveAs(path.join(out, 'invest-export-test.json'));
  const exported=JSON.parse(fs.readFileSync(path.join(out, 'invest-export-test.json'),'utf8'));
  assert(exported.dataset.id&&exported.backtests.length===1&&!exported.accounts&&!exported.notes);
  record('JSON导出包含可复现回测且不包含私人账本');
  await page.reload({waitUntil:'networkidle'});
  assert(await page.locator('#dataset-select').inputValue());
  await page.locator('#tab-paper').click();
  await page.waitForFunction(()=>document.querySelector('#notes-list').textContent.includes('安全笔记'));
  record('刷新恢复数据、账户与笔记');
  await page.locator('#tab-data').click();
  await page.locator('#csv-file').setInputFiles(path.join(root, 'examples', 'SYNTHETIC_DEMO_prices.csv'));
  await page.locator('#calendar-file').setInputFiles(path.join(root, 'examples', 'SYNTHETIC_DEMO_calendar.csv'));
  await page.locator('#data-source').fill('明确标记：合成CSV验收，非真实行情');
  await page.locator('#import-form [name=raw_prices_confirmed]').check();
  await page.locator('#import-form [name=volume_shares_confirmed]').check();
  await page.locator('#import-form button[type=submit]').click();
  await page.waitForFunction(()=>document.querySelector('#provenance').textContent.includes('合成CSV验收'));
  record('CSV和独立交易日历导入');
  assert.equal(await page.locator('#fetch-tushare').isDisabled(),true);
  record('未配置真实凭据时在线导入状态准确');
  await page.setViewportSize({width:390,height:844});
  for(const tab of ['research','backtest','paper','data']) {
   await page.locator('#tab-'+tab).click();
   const sizes=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));
   assert(sizes.scroll<=sizes.w+1,JSON.stringify({tab,...sizes}));
  }
  await page.locator('#tab-research').click();
  await page.screenshot({path:path.join(out, 'invest-mobile.png'),fullPage:true});
  record('390px四页面无整页横向溢出');
  await page.locator('#tab-research').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator('#tab-backtest').getAttribute('aria-selected'),'true');
  record('键盘方向键切换标签页');
  assert.deepEqual(errors,[]);
  assert.deepEqual(failures,[]);
  console.log(JSON.stringify({status:'PASS',checks,errors,consoleErrors:failures},null,2));
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
